(ns hubble.config)

(def debug? ^boolean goog.DEBUG)

(goog-define app-url "default-value")
(goog-define api-url "default-value")
(goog-define branding-url "default-value")
(goog-define guide-url "default-value")
(goog-define media-url "default-value")
(goog-define cdn-url "default-value")
(goog-define cdn-url2 "default-value")
(goog-define customer-api-url "default-value")
(goog-define version "#DEVELOPMENT_VERSION#")
(goog-define cke-upload-url "default-value")
(goog-define cke-web-socket-url "default-value")
(goog-define virtual-room-url "default-value")
(goog-define i18n-url "default-value")
(goog-define env "master")
(goog-define user-pool-id "")
(goog-define user-pool-web-client-id "")
(goog-define identity-pool-id "")
(goog-define aws-appsync-graphql-endpoint "")
(goog-define aws-appsync-region "")
(goog-define aws-appsync-authentication-type "")
(goog-define aws-appsync-api-key "")
(goog-define cognito-domain "")
(goog-define cms-url "https://cms-ci.obrizum.io")
(goog-define certificate-url "default-value")
(goog-define paddle-vendor "vendor-id")
(goog-define paddle-is-sandbox "is-sandbox-mode")
(def breaking-point-config {:breakpoints [:xs 576 :sm 768 :md 992 :lg 1200 :xl]
                            :debounce-ms 166})
